### ISSUE TITLE
Your repo will not compile

### ISSUE THREAD

**Issue by callen5914** [srmainwaring/steer_bot#7]
Greetings,

I followed your read me and attempted to compile and it fails.

`error: invalid initialization of reference of type ‘const boost::shared_ptr<const urdf::Link>&’ from expression of type ‘urdf::LinkConstSharedPtr {aka std::shared_ptr<const urdf::Link>}’`

`error: conversion from ‘urdf::JointConstSharedPtr {aka std::shared_ptr<const urdf::Joint>}’ to non-scalar type ‘boost::shared_ptr<const urdf::Joint>’ requested`

`error: no matching function for call to ‘getJointLimits(boost::shared_ptr<const urdf::Joint>&, joint_limits_interface::JointLimits&)’`

`error: no matching function for call to ‘getSoftJointLimits(boost::shared_ptr<const urdf::Joint>&, joint_limits_interface::SoftJointLimits&)’`

**Comment by srmainwaring** [comment]
The steer_bot example only contains a robot description and configuration for ros_control, gazebo, and rviz. There are no compiled components.

I suspect the compile error you are seeing is coming from the dependency https://github.com/tsedl/steer_drive_ros.git. Could you please confirm and provide some more info about the package and module that is not compiling. Then we can take it from there.

**Comment by srmainwaring** [comment]
@callen5914 I've updated the install instructions which should address this issue.

The compile errors you are seeing arise when building the `kinetic-devel` branch of `steer_drive_ros` package under ROS melodic. You need to checkout the melodic branch of this repo. I also recommend running `rosdep check` to ensure all system dependencies are in place. The package `stepback_and_steerturn_recovery` in `steer_drive_ros` has a dependency on the navigation stack, it's not needed for this example so you could blacklist it in catkin to prevent the error, or ensure the dependencies are there.

There is another potential issue I noticed when running this on an Ubuntu 18.04.4 VM, and that is there was an ABI breaking change in `ros_control` discussed here:
[https://discourse.ros.org/t/ros-control-abi-breakage-in-melodic-2020-02/12681](https://discourse.ros.org/t/ros-control-abi-breakage-in-melodic-2020-02/12681)
which manifests as a segfault when launching Gazebo. If you see this error the fix is to upgrade your ROS packages:

```bash
sudo apt-get --only-upgrade install ros-*
```
